#ifndef _INCLUDE_BLOCKS_H
#define _INCLUDE_BLOCKS_H

enum COLOURS { CYAN, BLUE, ORANGE, YELLOW, GREEN, PURPLE };
enum SHAPES { SHAPE_I, SHAPE_J, SHAPE_L, SHAPE_O, SHAPE_S, SHAPE_T, SHAPE_Z };

#endif	// _INCLUDE_BLOCKS_H
